[
  {
    "owner": "Akash",
    "exception": "java.lang.AssertionError: Order ID is null due to sync delay expected object to not be null",
    "file_path": "src/test/java/com/prathamesh/services/OrderServiceTest.java",
    "test_class": "com.prathamesh.services.OrderServiceTest",
    "end_time": "Sun Aug 31 13:31:46 IST 2025",
    "priority": "High",
    "duration_ms": 8,
    "start_time": "Sun Aug 31 13:31:46 IST 2025",
    "stacktrace": "[org.testng.Assert.fail(Assert.java:110), org.testng.Assert.assertTrue(Assert.java:1319), com.prathamesh.services.OrderServiceTest.testGetOrderStatus_syncIssue(OrderServiceTest.java:20), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:566), org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139), org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677), org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221), org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50), org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969), org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194), org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148), org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128), java.base/java.util.ArrayList.forEach(ArrayList.java:1541), org.testng.TestRunner.privateRun(TestRunner.java:829), org.testng.TestRunner.run(TestRunner.java:602), org.testng.SuiteRunner.runTest(SuiteRunner.java:437), org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431), org.testng.SuiteRunner.privateRun(SuiteRunner.java:391), org.testng.SuiteRunner.run(SuiteRunner.java:330), org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52), org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95), org.testng.TestNG.runSuitesSequentially(TestNG.java:1256), org.testng.TestNG.runSuitesLocally(TestNG.java:1176), org.testng.TestNG.runSuites(TestNG.java:1099), org.testng.TestNG.run(TestNG.java:1067), com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66), com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)]",
    "service": "OrderService",
    "test_method": "testGetOrderStatus",
    "status": "FAILED",
    "desc": "Order status check"
  },
  {
    "owner": "Akash",
    "exception": "java.lang.AssertionError: expected [true] but found [false]",
    "file_path": "src/test/java/com/prathamesh/services/OrderServiceTest.java",
    "test_class": "com.prathamesh.services.OrderServiceTest",
    "end_time": "Sun Aug 31 13:31:48 IST 2025",
    "priority": "Low",
    "duration_ms": 2410,
    "start_time": "Sun Aug 31 13:31:46 IST 2025",
    "stacktrace": "[org.testng.Assert.fail(Assert.java:110), org.testng.Assert.failNotEquals(Assert.java:1413), org.testng.Assert.assertTrue(Assert.java:56), org.testng.Assert.assertTrue(Assert.java:66), com.prathamesh.services.OrderServiceTest.testOrderHistory_shouldPass(OrderServiceTest.java:40), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:566), org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139), org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677), org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221), org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50), org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969), org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194), org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148), org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128), java.base/java.util.ArrayList.forEach(ArrayList.java:1541), org.testng.TestRunner.privateRun(TestRunner.java:829), org.testng.TestRunner.run(TestRunner.java:602), org.testng.SuiteRunner.runTest(SuiteRunner.java:437), org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431), org.testng.SuiteRunner.privateRun(SuiteRunner.java:391), org.testng.SuiteRunner.run(SuiteRunner.java:330), org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52), org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95), org.testng.TestNG.runSuitesSequentially(TestNG.java:1256), org.testng.TestNG.runSuitesLocally(TestNG.java:1176), org.testng.TestNG.runSuites(TestNG.java:1099), org.testng.TestNG.run(TestNG.java:1067), com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66), com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)]",
    "service": "OrderService",
    "test_method": "testOrderHistory_shouldPass",
    "status": "FAILED",
    "desc": "Successful order history retrieval"
  },
  {
    "owner": "Akash",
    "exception": "java.lang.AssertionError: Expected 201 Created, got 415 expected [201] but found [415]",
    "file_path": "src/test/java/com/prathamesh/services/OrderServiceTest.java",
    "test_class": "com.prathamesh.services.OrderServiceTest",
    "end_time": "Sun Aug 31 13:31:49 IST 2025",
    "priority": "Medium",
    "duration_ms": 761,
    "start_time": "Sun Aug 31 13:31:48 IST 2025",
    "stacktrace": "[org.testng.Assert.fail(Assert.java:110), org.testng.Assert.failNotEquals(Assert.java:1413), org.testng.Assert.assertEqualsImpl(Assert.java:149), org.testng.Assert.assertEquals(Assert.java:131), org.testng.Assert.assertEquals(Assert.java:1240), com.prathamesh.services.OrderServiceTest.testPlaceOrder_assertionFail(OrderServiceTest.java:33), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:566), org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139), org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677), org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221), org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50), org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969), org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194), org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148), org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128), java.base/java.util.ArrayList.forEach(ArrayList.java:1541), org.testng.TestRunner.privateRun(TestRunner.java:829), org.testng.TestRunner.run(TestRunner.java:602), org.testng.SuiteRunner.runTest(SuiteRunner.java:437), org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431), org.testng.SuiteRunner.privateRun(SuiteRunner.java:391), org.testng.SuiteRunner.run(SuiteRunner.java:330), org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52), org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95), org.testng.TestNG.runSuitesSequentially(TestNG.java:1256), org.testng.TestNG.runSuitesLocally(TestNG.java:1176), org.testng.TestNG.runSuites(TestNG.java:1099), org.testng.TestNG.run(TestNG.java:1067), com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66), com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)]",
    "service": "OrderService",
    "test_method": "testPlaceOrder_assertionFail",
    "status": "FAILED",
    "desc": "Order placement status assertion"
  },
  {
    "owner": "Manisha",
    "exception": "java.lang.AssertionError: 1 expectation failed.\nExpected status code <200> but was <500>.\n",
    "file_path": "src/test/java/com/prathamesh/services/PaymentServiceTest.java",
    "test_class": "com.prathamesh.services.PaymentServiceTest",
    "end_time": "Sun Aug 31 13:31:50 IST 2025",
    "priority": "High",
    "duration_ms": 857,
    "start_time": "Sun Aug 31 13:31:49 IST 2025",
    "stacktrace": "[java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method), java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62), java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45), java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490), org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73), org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60), org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86), org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:58), org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263), org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277), io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512), io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source), org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:46), org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125), org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139), io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696), io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:566), org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43), org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198), org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62), org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:50), org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171), org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185), io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135), io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source), org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:50), org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171), org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185), io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143), io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89), com.prathamesh.utils.PaymentService.getPayments(PaymentService.java:11), com.prathamesh.services.PaymentServiceTest.testGetPayments_shouldPass(PaymentServiceTest.java:17), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:566), org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139), org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677), org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221), org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50), org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969), org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194), org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148), org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128), java.base/java.util.ArrayList.forEach(ArrayList.java:1541), org.testng.TestRunner.privateRun(TestRunner.java:829), org.testng.TestRunner.run(TestRunner.java:602), org.testng.SuiteRunner.runTest(SuiteRunner.java:437), org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431), org.testng.SuiteRunner.privateRun(SuiteRunner.java:391), org.testng.SuiteRunner.run(SuiteRunner.java:330), org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52), org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95), org.testng.TestNG.runSuitesSequentially(TestNG.java:1256), org.testng.TestNG.runSuitesLocally(TestNG.java:1176), org.testng.TestNG.runSuites(TestNG.java:1099), org.testng.TestNG.run(TestNG.java:1067), com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66), com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)]",
    "service": "PaymentService",
    "test_method": "testGetPayments_shouldPass",
    "status": "FAILED",
    "desc": "Get all payments"
  },
  {
    "owner": "Manisha",
    "exception": null,
    "file_path": "src/test/java/com/prathamesh/services/PaymentServiceTest.java",
    "test_class": "com.prathamesh.services.PaymentServiceTest",
    "end_time": "Sun Aug 31 13:31:50 IST 2025",
    "priority": "Critical",
    "duration_ms": 0,
    "start_time": "Sun Aug 31 13:31:50 IST 2025",
    "stacktrace": null,
    "service": "PaymentService",
    "test_method": "testPaymentGateway_shouldFail",
    "status": "PASSED",
    "desc": "Failing payment gateway test"
  },
  {
    "owner": "Manisha",
    "exception": null,
    "file_path": "src/test/java/com/prathamesh/services/PaymentServiceTest.java",
    "test_class": "com.prathamesh.services.PaymentServiceTest",
    "end_time": "Sun Aug 31 13:31:50 IST 2025",
    "priority": "Medium",
    "duration_ms": 493,
    "start_time": "Sun Aug 31 13:31:50 IST 2025",
    "stacktrace": null,
    "service": "PaymentService",
    "test_method": "testRefundStatus_shouldPass",
    "status": "PASSED",
    "desc": "Refund status check"
  },
  {
    "owner": "Samay",
    "exception": "java.lang.NullPointerException",
    "file_path": "src/test/java/com/prathamesh/services/UserServiceTest.java",
    "test_class": "com.prathamesh.services.UserServiceTest",
    "end_time": "Sun Aug 31 13:31:50 IST 2025",
    "priority": "Medium",
    "duration_ms": 0,
    "start_time": "Sun Aug 31 13:31:50 IST 2025",
    "stacktrace": "[com.prathamesh.services.UserServiceTest.testCreateUser_nullInput_shouldFail(UserServiceTest.java:32), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:566), org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139), org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677), org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221), org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50), org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969), org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194), org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148), org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128), java.base/java.util.ArrayList.forEach(ArrayList.java:1541), org.testng.TestRunner.privateRun(TestRunner.java:829), org.testng.TestRunner.run(TestRunner.java:602), org.testng.SuiteRunner.runTest(SuiteRunner.java:437), org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431), org.testng.SuiteRunner.privateRun(SuiteRunner.java:391), org.testng.SuiteRunner.run(SuiteRunner.java:330), org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52), org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95), org.testng.TestNG.runSuitesSequentially(TestNG.java:1256), org.testng.TestNG.runSuitesLocally(TestNG.java:1176), org.testng.TestNG.runSuites(TestNG.java:1099), org.testng.TestNG.run(TestNG.java:1067), com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66), com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)]",
    "service": "UserService",
    "test_method": "testCreateUser_nullInput_shouldFail",
    "status": "FAILED",
    "desc": "Null input simulation"
  },
  {
    "owner": "Samay",
    "exception": null,
    "file_path": "src/test/java/com/prathamesh/services/UserServiceTest.java",
    "test_class": "com.prathamesh.services.UserServiceTest",
    "end_time": "Sun Aug 31 13:31:51 IST 2025",
    "priority": "Low",
    "duration_ms": 897,
    "start_time": "Sun Aug 31 13:31:50 IST 2025",
    "stacktrace": null,
    "service": "UserService",
    "test_method": "testDeleteUser_shouldPass",
    "status": "PASSED",
    "desc": "User deletion flow"
  },
  {
    "owner": "Samay",
    "exception": "java.lang.RuntimeException:  500 Internal Server Error",
    "file_path": "src/test/java/com/prathamesh/services/UserServiceTest.java",
    "test_class": "com.prathamesh.services.UserServiceTest",
    "end_time": "Sun Aug 31 13:31:51 IST 2025",
    "priority": "High",
    "duration_ms": 1,
    "start_time": "Sun Aug 31 13:31:51 IST 2025",
    "stacktrace": "[com.prathamesh.utils.UserService.s500Error(UserService.java:17), com.prathamesh.services.UserServiceTest.testGetUserProfile(UserServiceTest.java:21), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:566), org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139), org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677), org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221), org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50), org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969), org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194), org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148), org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128), java.base/java.util.ArrayList.forEach(ArrayList.java:1541), org.testng.TestRunner.privateRun(TestRunner.java:829), org.testng.TestRunner.run(TestRunner.java:602), org.testng.SuiteRunner.runTest(SuiteRunner.java:437), org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431), org.testng.SuiteRunner.privateRun(SuiteRunner.java:391), org.testng.SuiteRunner.run(SuiteRunner.java:330), org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52), org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95), org.testng.TestNG.runSuitesSequentially(TestNG.java:1256), org.testng.TestNG.runSuitesLocally(TestNG.java:1176), org.testng.TestNG.runSuites(TestNG.java:1099), org.testng.TestNG.run(TestNG.java:1067), com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66), com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)]",
    "service": "UserService",
    "test_method": "testGetUserProfile",
    "status": "FAILED",
    "desc": "Validates user profile API"
  }
]