[
  {
    "owner": "Samay",
    "exception": "java.lang.NullPointerException",
    "file_path": "src/test/java/com/prathamesh/services/UserServiceTest.java",
    "test_class": "com.prathamesh.services.UserServiceTest",
    "end_time": "Sun Aug 17 15:29:08 IST 2025",
    "priority": "Medium",
    "duration_ms": 7,
    "start_time": "Sun Aug 17 15:29:08 IST 2025",
    "stacktrace": "[com.prathamesh.services.UserServiceTest.testCreateUser_nullInput_shouldFail(UserServiceTest.java:31), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:566), org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139), org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677), org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221), org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50), org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969), org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194), org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148), org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]",
    "service": "UserService",
    "test_method": "testCreateUser_nullInput_shouldFail",
    "status": "FAILED",
    "desc": "Null input simulation"
  },
  {
    "owner": "Manisha",
    "exception": null,
    "file_path": "src/test/java/com/prathamesh/services/PaymentServiceTest.java",
    "test_class": "com.prathamesh.services.PaymentServiceTest",
    "end_time": "Sun Aug 17 15:29:10 IST 2025",
    "priority": "High",
    "duration_ms": 1574,
    "start_time": "Sun Aug 17 15:29:08 IST 2025",
    "stacktrace": null,
    "service": "PaymentService",
    "test_method": "testGetPayments_shouldPass",
    "status": "PASSED",
    "desc": "Get all payments"
  },
  {
    "owner": "Samay",
    "exception": null,
    "file_path": "src/test/java/com/prathamesh/services/UserServiceTest.java",
    "test_class": "com.prathamesh.services.UserServiceTest",
    "end_time": "Sun Aug 17 15:29:10 IST 2025",
    "priority": "Low",
    "duration_ms": 1529,
    "start_time": "Sun Aug 17 15:29:09 IST 2025",
    "stacktrace": null,
    "service": "UserService",
    "test_method": "testDeleteUser_shouldPass",
    "status": "PASSED",
    "desc": "User deletion flow"
  },
  {
    "owner": "Akash",
    "exception": null,
    "file_path": "src/test/java/com/prathamesh/services/OrderServiceTest.java",
    "test_class": "com.prathamesh.services.OrderServiceTest",
    "end_time": "Sun Aug 17 15:29:10 IST 2025",
    "priority": "High",
    "duration_ms": 1601,
    "start_time": "Sun Aug 17 15:29:08 IST 2025",
    "stacktrace": null,
    "service": "OrderService",
    "test_method": "testGetOrderStatus_syncIssue",
    "status": "PASSED",
    "desc": "Order status check with sync delay"
  },
  {
    "owner": "Samay",
    "exception": null,
    "file_path": "src/test/java/com/prathamesh/services/UserServiceTest.java",
    "test_class": "com.prathamesh.services.UserServiceTest",
    "end_time": "Sun Aug 17 15:29:10 IST 2025",
    "priority": "High",
    "duration_ms": 198,
    "start_time": "Sun Aug 17 15:29:10 IST 2025",
    "stacktrace": null,
    "service": "UserService",
    "test_method": "testGetUserProfile",
    "status": "PASSED",
    "desc": "Validates user profile API"
  },
  {
    "owner": "Manisha",
    "exception": "java.lang.AssertionError: Payment gateway route failed! expected [200] but found [500]",
    "file_path": "src/test/java/com/prathamesh/services/PaymentServiceTest.java",
    "test_class": "com.prathamesh.services.PaymentServiceTest",
    "end_time": "Sun Aug 17 15:29:10 IST 2025",
    "priority": "Critical",
    "duration_ms": 205,
    "start_time": "Sun Aug 17 15:29:10 IST 2025",
    "stacktrace": "[org.testng.Assert.fail(Assert.java:110), org.testng.Assert.failNotEquals(Assert.java:1413), org.testng.Assert.assertEqualsImpl(Assert.java:149), org.testng.Assert.assertEquals(Assert.java:131), org.testng.Assert.assertEquals(Assert.java:1240), com.prathamesh.services.PaymentServiceTest.testPaymentGateway_shouldFail(PaymentServiceTest.java:24), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:566), org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139), org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677), org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221), org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50), org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969), org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194), org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148), org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]",
    "service": "PaymentService",
    "test_method": "testPaymentGateway_shouldFail",
    "status": "PASSED_ON_RETRY",
    "desc": "Failing payment gateway test"
  },
  {
    "owner": "Akash",
    "exception": "java.lang.AssertionError: expected [true] but found [false]",
    "file_path": "src/test/java/com/prathamesh/services/OrderServiceTest.java",
    "test_class": "com.prathamesh.services.OrderServiceTest",
    "end_time": "Sun Aug 17 15:29:10 IST 2025",
    "priority": "Low",
    "duration_ms": 186,
    "start_time": "Sun Aug 17 15:29:10 IST 2025",
    "stacktrace": "[org.testng.Assert.fail(Assert.java:110), org.testng.Assert.failNotEquals(Assert.java:1413), org.testng.Assert.assertTrue(Assert.java:56), org.testng.Assert.assertTrue(Assert.java:66), com.prathamesh.services.OrderServiceTest.testOrderHistory_shouldPass(OrderServiceTest.java:41), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:566), org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139), org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677), org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221), org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50), org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969), org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194), org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148), org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]",
    "service": "OrderService",
    "test_method": "testOrderHistory_shouldPass",
    "status": "FAILED",
    "desc": "Successful order history retrieval"
  },
  {
    "owner": "Manisha",
    "exception": null,
    "file_path": "src/test/java/com/prathamesh/services/PaymentServiceTest.java",
    "test_class": "com.prathamesh.services.PaymentServiceTest",
    "end_time": "Sun Aug 17 15:29:10 IST 2025",
    "priority": "Medium",
    "duration_ms": 170,
    "start_time": "Sun Aug 17 15:29:10 IST 2025",
    "stacktrace": null,
    "service": "PaymentService",
    "test_method": "testRefundStatus_shouldPass",
    "status": "PASSED",
    "desc": "Refund status check"
  },
  {
    "owner": "Akash",
    "exception": "java.lang.AssertionError: Expected 201 Created, got 415 expected [201] but found [415]",
    "file_path": "src/test/java/com/prathamesh/services/OrderServiceTest.java",
    "test_class": "com.prathamesh.services.OrderServiceTest",
    "end_time": "Sun Aug 17 15:29:10 IST 2025",
    "priority": "Medium",
    "duration_ms": 189,
    "start_time": "Sun Aug 17 15:29:10 IST 2025",
    "stacktrace": "[org.testng.Assert.fail(Assert.java:110), org.testng.Assert.failNotEquals(Assert.java:1413), org.testng.Assert.assertEqualsImpl(Assert.java:149), org.testng.Assert.assertEquals(Assert.java:131), org.testng.Assert.assertEquals(Assert.java:1240), com.prathamesh.services.OrderServiceTest.testPlaceOrder_assertionFail(OrderServiceTest.java:34), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:566), org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139), org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677), org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221), org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50), org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969), org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194), org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148), org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]",
    "service": "OrderService",
    "test_method": "testPlaceOrder_assertionFail",
    "status": "FAILED",
    "desc": "Order placement status assertion"
  }
]